server:
  port: 8088

spring:
  application:
    name: tenant-service
  
  config:
    import: "optional:configserver:http://localhost:8888/"

  datasource:
    url: jdbc:mysql://localhost:3306/omnichat_tenant?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
