CREATE TABLE channel_connections (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    platform ENUM('FACEBOOK', 'ZALO', 'SHOPEE', 'TIKTOK') NOT NULL,
    page_name VARCHAR(255) NOT NULL,
    access_token TEXT NOT NULL,
    refresh_token TEXT,
    status ENUM('CONNECTED', 'DISCONNECTED', 'ERROR') DEFAULT 'CONNECTED',
    expiry_date DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
